server:
  port: 8001
  servlet:
    context-path: /paymentService

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.37.128:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    # 表示将自己注册进eurekaServer，默认为true
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，默认为true
    # 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka # 注册进单机版eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001 # 服务名称显示为payment8001，不添加此配置显示主机名:服务名称
    prefer-ip-address: true # 访问路径可以显示ip地址
    # eureka客户端向eureka服务端发送心跳的时间间隔，默认30s，现在改为1秒
    lease-renewal-interval-in-seconds: 1
    # eureka服务端在收到最后一次心跳后等待时间上限，默认为90s，超时eureka将该服务删除，这里改为2秒
    lease-expiration-duration-in-seconds: 2

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.liurk.springcloud.entities    # 所有Entity别名类所在包

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liurk.springcloud.entry    # 所有Entity别名类所在包