server:
  port: 7001
eureka:
  instance:
    # eureka服务端的实例名称
#    hostname: localhost # 单机时使用
    hostname: eureka7001.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 配置eurekaServer交互的地址，查询和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 单机时使用
      defaultZone: http://eureka7002.com:7002/eureka/ # 相互注册，要将eureka7001注册进eureka7002
  server:
    # 关闭eureka自我保护
    enable-self-preservation: false
    # 2秒钟
    eviction-interval-timer-in-ms: 2000

